namespace Turso.Client.PlatformAPI.APITokens.Models;

/// <summary>
///     The response from the CreateApiToken endpoint. See https://docs.turso.tech/api-reference/tokens/create
/// </summary>
public class CreateApiTokenResponse
{
    /// <summary>
    ///     The ID generated by Turso for the API Token.
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    ///     The name given to the API Token.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    ///     The actual token contents as a JWT. This is used with the Bearer header, see
    ///     <a href="https://docs.turso.tech/authentication">Authentication</a> for more details.
    ///     This token is never revealed again.
    /// </summary>
    public string Token { get; set; }
}